Repository TACC/Core-Styles, pull requests merged in 2023-11, with the labels that each got.

#252 fix: c-card--frontera variant misc bugs
  dist/components/c-card--frontera-about-page.css
  dist/core-styles.cms.css
  src/lib/_imports/components/c-card--frontera-about-page.css
  src/lib/_imports/components/c-card/c-card--frontera.hbs
  src/lib/_imports/components/c-card/config.yml
Labels: fix, patch

#251 feat/tup 617: Migrate c-card fixes to core-styles
  dist/components/c-card.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  src/lib/_imports/components/c-card.css
Labels: feature, minor

#253 fix: tup-639 move c-button font-weight bold to cms
  dist/components/c-button.css
  dist/components/c-card.css
  dist/components/c-form--login.css
  dist/components/c-form.css
  dist/components/django-cms-forms.css
  dist/core-styles.base.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  dist/trumps/s-form--login.css
  dist/trumps/s-form.css
  src/lib/_imports/components/c-button.css
  src/lib/_imports/components/c-card.css
Labels: fix, patch

#249 feat/tup 627: Migrate s-header to core-styles
  dist/core-styles.header.css
  dist/trumps/s-header.bootstrap.css
  dist/trumps/s-header.css
  src/lib/_imports/trumps/s-header.bootstrap.css
  src/lib/_imports/trumps/s-header.css
Labels: feature, minor

#254 feat/tup-636: Migrate c-card--images to core-styles
  dist/components/c-card--from-tup-cms.css
  dist/components/c-card.css
  dist/components/c-card/c-card--images.css
  dist/components/c-card/c-card--images.demo.css
  dist/components/c-card/c-card--images/c-card--images.demo.css
  dist/components/c-card/c-card-images.demo.css
  dist/components/c-card/c-card.demo.images.css
  dist/components/c-card/card-images/c-card--images.demo.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  src/lib/_imports/components/c-card--from-tup-cms.css
  src/lib/_imports/components/c-card.css
  src/lib/_imports/components/c-card/_c-card--image-bottom-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-bottom-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image-left-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-left-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image-right-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-right-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image-top-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-top-staff-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-top-staff-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image-top-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--one-image.hbs
  src/lib/_imports/components/c-card/_c-card--one-with-grid.hbs
  src/lib/_imports/components/c-card/c-card--images.hbs
  src/lib/_imports/components/c-card/c-card.demo.images.css
  src/lib/_imports/core-styles.docs.css
Labels: feature, minor

#250 feat/tup 637: Migrate c-card support list to core-styles
  dist/components/c-card.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  src/lib/_imports/components/c-card.css
  src/lib/_imports/components/c-card/_c-card--many-variable.hbs
Labels: feature, minor

#258 feat/tup-635: Add header demo to core-styles
  dist/core-styles.header.css
  dist/trumps/s-header/s-header--with-branding.demo.css
  dist/trumps/s-header/s-header.demo.css
  dist/trumps/s-portal-nav.css
  src/lib/_imports/trumps/_s-cms-nav/_s-cms-nav.hbs
  src/lib/_imports/trumps/_s-portal-nav/_s-portal-nav.hbs
  src/lib/_imports/trumps/_tacc-search-bar/_tacc-search-bar.hbs
  src/lib/_imports/trumps/s-header.html
  src/lib/_imports/trumps/s-header/config.yml
  src/lib/_imports/trumps/s-header/s-header--with-branding.hbs
  src/lib/_imports/trumps/s-header/s-header.demo.css
  src/lib/_imports/trumps/s-header/s-header.hbs
  src/lib/_imports/trumps/s-portal-nav.css
Labels: feature, minor

#256 hotfix: tup 644 footer not sticky during edge case
  dist/core-styles.cms.css
  dist/core-styles.portal.css
  dist/elements/sticky-footer.css
  dist/elements/sticky-footer/demo.css
  src/lib/_imports/elements/sticky-footer.css
  src/lib/_imports/elements/sticky-footer/demo.css
  src/lib/_imports/elements/sticky-footer/sticky-footer.hbs
Labels: fix, patch

#261 feat/tup-648 Migrate u-header from tup-ui to core-stlyes
  dist/core-styles.base.css
  dist/trumps/u-highlight.css
  dist/trumps/u-highlight/u-highlight.demo.css
  src/lib/_imports/core-styles.base.css
  src/lib/_imports/trumps/u-highlight.css
  src/lib/_imports/trumps/u-highlight/readme.md
  src/lib/_imports/trumps/u-highlight/u-highlight.demo.css
  src/lib/_imports/trumps/u-highlight/u-highlight.hbs
Labels: feature, minor

#260 feat/tup-486 Create text-wrap for longer links
  dist/components/c-card.css
  dist/components/cortal.icon.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  dist/core-styles.portal.css
  src/lib/_imports/components/c-card.css
  src/lib/_imports/components/cortal.icon.css
Labels: feature, minor

#264 bug/tup-649 bug/tup-646 Remove unwanted padding-left
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  dist/elements/html-elements.cms.css
  src/lib/_imports/elements/html-elements.cms.css
Labels: fix, minor

#265 fix: tup-488 scrollable table border
  dist/core-styles.base.css
  dist/elements/table--basic.css
  dist/elements/table.css
  src/lib/_imports/elements/table--basic.css
  src/lib/_imports/elements/table.cms.css
Labels: fix, patch

#257 chore: tup-636 c-card--image - less templates
  src/lib/_imports/components/c-card/_c-card--image-bottom-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-bottom-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image-left-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-left-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image-right-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-right-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image-top-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-top-staff-plain.hbs
  src/lib/_imports/components/c-card/_c-card--image-top-staff-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image-top-transparent.hbs
  src/lib/_imports/components/c-card/_c-card--image.hbs
  src/lib/_imports/components/c-card/c-card--images.hbs
  src/lib/_imports/components/c-card/config.yml
Labels: refactor, patch

#267 fix: tup-659 all form fields too short
  dist/components/c-form--login.css
  dist/components/c-form.css
  dist/components/django-cms-forms.css
  dist/core-styles.base.css
  dist/trumps/s-form--login.css
  dist/trumps/s-form.css
  src/lib/_imports/components/c-form--login.css
  src/lib/_imports/components/c-form.css
  src/lib/_imports/components/django-cms-forms.css
Labels: fix, patch

#268 hotfix: django-cms-forms unstyled in demo
  dist/components/django-cms-forms.css
  src/lib/_imports/components/django-cms-forms.css
  src/lib/_imports/components/django-cms-forms/config.yml
Labels: fix, patch

#269 Fix/tup 660 form badge font size zero can remove all space
  dist/components/c-form.css
  dist/core-styles.base.css
  dist/trumps/s-form.css
  src/lib/_imports/components/c-form.css
Labels: fix, patch

#271 hotfix: tup-660 increase cms form badge space
  dist/components/django-cms-forms.css
  src/lib/_imports/components/django-cms-forms.css
Labels: fix, patch

#272 feat: do NOT truncate buttons by default
  dist/components/c-button.css
  dist/components/c-form--login.css
  dist/components/c-form.css
  dist/core-styles.base.css
  dist/trumps/s-form--login.css
  dist/trumps/s-form.css
  src/lib/_imports/components/c-button.css
  src/lib/_imports/components/c-button.selectors.css
  src/lib/_imports/components/c-button/config.yml
Labels: feature, minor
