Repository TACC/Core-Styles, pull requests merged in 2023-10, with the labels that each got.

#240 feat: support s-form-page footer link with image
  dist/core-styles.portal.css
  dist/trumps/s-form-page.css
  src/lib/_imports/trumps/s-form-page.css
  src/lib/_imports/trumps/s-form-page/_s-form-page--footer.hbs
  src/lib/_imports/trumps/s-form-page/s-form-page--login.hbs
  src/lib/_imports/trumps/s-form-page/s-form-page.hbs
Labels: feature, minor

#241 chore: v2.18.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#243 docs: allow small primary buttons
  src/lib/_imports/components/c-button/c-button.hbs
Labels: documentation, patch

#245 feat: tup-619 c-content-block migration
  dist/components/c-content-block.css
  dist/core-styles.cms.css
  src/lib/_imports/components/c-content-block.css
  src/lib/_imports/components/c-content-block/c-content-block.hbs
  src/lib/_imports/core-styles.cms.css
Labels: feature, minor

#246 feat: tup-463 c-content-block and generics/attributes from tup-ui
  dist/components/c-button.css
  dist/components/c-content-block.css
  dist/components/c-form--login.css
  dist/components/c-form.css
  dist/components/django-cms-forms.css
  dist/core-styles.base.css
  dist/core-styles.cms.css
  dist/generics/attributes.css
  dist/generics/attributes/attributes.css
  dist/generics/attributes/demo.css
  dist/trumps/s-form--login.css
  dist/trumps/s-form.css
  src/lib/_imports/components/c-button.css
  src/lib/_imports/components/c-button/c-button.hbs
  src/lib/_imports/components/c-content-block.css
  src/lib/_imports/components/c-content-block/c-content-block.hbs
  src/lib/_imports/core-styles.base.css
  src/lib/_imports/core-styles.cms.css
  src/lib/_imports/generics/attributes.css
  src/lib/_imports/generics/attributes/attributes.hbs
  src/lib/_imports/generics/attributes/demo.css
  src/lib/_imports/generics/attributes/readme.md
Labels: feature, minor

#247 feat: tup-624 c-update migration
  dist/components/c-update.css
  dist/core-styles.base.css
  dist/core-styles.cms.css
  dist/elements/table--basic.css
  dist/elements/table--nested.css
  dist/elements/table.css
  dist/trumps/s-image-grid.css
  dist/trumps/s-inline-dl.css
  package-lock.json
  src/lib/_imports/components/c-update.css
  src/lib/_imports/components/c-update/c-update.hbs
  src/lib/_imports/components/c-update/config.yml
  src/lib/_imports/components/c-update/readme.md
  src/lib/_imports/core-styles.cms.css
Labels: minor

#248 feat/tup-625: Migrate o-heading-steps to core-styles
  dist/core-styles.cms.css
  dist/objects/o-heading-steps.css
  src/lib/_imports/core-styles.cms.css
  src/lib/_imports/objects/o-heading-steps.css
  src/lib/_imports/objects/o-heading-steps/config.yml
  src/lib/_imports/objects/o-heading-steps/o-heading-steps.hbs
  src/lib/_imports/objects/o-heading-steps/readme.md
Labels: feature, minor
