Repository TACC/Core-Styles, pull requests merged in 2024-01, with the labels that each got.

#288 fix: monospace inline link needs styles
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  src/lib/_imports/elements/monospace.css
  src/lib/_imports/elements/monospace/monospace.hbs
Labels: patch

#291 feat: reduce CSS in Core-CMS
  dist/components/c-button--cms.css
  dist/core-styles.base.css
  dist/core-styles.cms.css
  dist/core-styles.settings.css
  dist/core-styles.wysiwyg.css
  dist/elements/irregular-link.css
  dist/elements/mailto-link.css
  dist/settings/color.css
  dist/trumps/s-drop-cap.css
  src/lib/_imports/components/c-button--cms.css
  src/lib/_imports/components/django-cms-forms.hacks.css
  src/lib/_imports/core-styles.cms.css
  src/lib/_imports/elements/irregular-link.css
  src/lib/_imports/elements/mailto-link.css
  src/lib/_imports/settings/color.css
  src/lib/_imports/tools/media-queries.css
  src/lib/_imports/trumps/s-drop-cap.css
  src/lib/_imports/trumps/s-drop-cap/config.yml
  src/lib/_imports/trumps/s-drop-cap/readme.md
  src/lib/_imports/trumps/s-drop-cap/s-drop-cap.hbs
Labels: feature

#290 task/tup-673 Vertically align icon
  dist/components/cortal.icon.css
  dist/core-styles.cms.css
  dist/core-styles.portal.css
  src/lib/_imports/components/cortal.icon.css
Labels: minor, style

#289 Task/tup-674 Fix hanging indent
  dist/components/c-card.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  src/lib/_imports/components/c-card.css
Labels: fix, minor

#293 refactor: more icon alignment
  dist/components/c-button.css
  dist/components/c-card.css
  dist/components/c-form--login.css
  dist/components/c-form.css
  dist/components/cortal.icon.css
  dist/core-styles.base.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  dist/core-styles.portal.css
  dist/trumps/s-form--login.css
  dist/trumps/s-form.css
  src/lib/_imports/components/c-button.css
  src/lib/_imports/components/c-card.css
  src/lib/_imports/components/c-card/_c-card--many-variable.hbs
  src/lib/_imports/components/cortal.icon.css
Labels: refactor, patch

#297 refactor: c-card--image-bottom
  dist/components/c-card.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  src/lib/_imports/components/c-card.css
  src/lib/_imports/components/c-card/c-card.readme.md
  src/lib/_imports/components/c-card/config.yml
Labels: refactor, patch

#294 fix: publish contact card styles
  dist/components/c-card.css
  dist/components/c-card/c-card.demo.images.css
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  src/lib/_imports/components/c-card.css
  src/lib/_imports/components/c-card/c-card.demo.images.css
Labels: fix, patch

#296 refactor: card image demo grid
  dist/components/c-card/c-card.demo.images.css
  src/lib/_imports/components/c-card/c-card--images.hbs
  src/lib/_imports/components/c-card/c-card.demo.images.css
  src/lib/_imports/components/c-card/config.yml
Labels: refactor, patch

#298 fix: CMS button--as-link has button padding
  dist/components/c-button--cms.css
  dist/core-styles.cms.css
  src/lib/_imports/components/c-button--cms.css
Labels: fix, patch

#301 fix: c-tag padding should be static and less
  dist/components/c-tag.css
  dist/core-styles.base.css
  src/lib/_imports/components/c-tag.css
Labels: fix, patch

#303 fix: load docs in base layer, like other clients
  fractal.config.js
Labels: fix, patch

#275 task/tup-534 Adds in media query for tables
  dist/core-styles.base.css
  dist/core-styles.cms.css
  dist/core-styles.portal.css
  dist/elements/table--basic.css
  dist/elements/table--nested.css
  dist/elements/table.cms.css
  dist/elements/table.css
  fractal.config.js
  src/lib/_imports/core-styles.cms.css
  src/lib/_imports/core-styles.portal.css
  src/lib/_imports/elements/table--basic.css
  src/lib/_imports/elements/table--nested.css
  src/lib/_imports/elements/table.cms.css
  src/lib/_imports/elements/table.portal.css
  src/lib/_imports/elements/table/config.yml
  src/lib/_imports/elements/table/table.hbs
  src/lib/_imports/trumps/s-paragraph-table/readme.md
  src/lib/_imports/trumps/s-truncated-table.css
  src/lib/_imports/trumps/s-truncated-table/config.yml
  src/lib/_imports/trumps/s-truncated-table/readme.md
  src/lib/_imports/trumps/s-truncated-table/s-truncated-table.hbs
Labels: enhancement, minor
