Repository TACC/Core-Styles, pull requests merged in 2024-03, with the labels that each got.

#310 hotfix: `<hr>` in blog hidden behind offset figure
  dist/core-styles.cms.css
  dist/core-styles.docs.css
  dist/elements/html-elements.cms.css
  src/lib/_imports/elements/html-elements.cms.css
Labels: fix, patch

#315 fix: CMD-79 navbar expanded can overflow header
  src/lib/_imports/trumps/s-header.css
Labels: fix

#319 CMD-111: Tomas: New Mobile Table UI is Not Backwards Compatible
  dist/core-styles.base.css
  dist/core-styles.cms.css
  dist/elements/table--basic.css
  dist/elements/table--nested.css
  dist/elements/table.cms.css
  dist/elements/table.css
  src/lib/_imports/elements/table--basic.css
  src/lib/_imports/elements/table--nested.css
  src/lib/_imports/elements/table.cms.css
Labels: feature, patch

#323 feat: cmd-111 support no header demo in mobile table
  dist/core-styles.base.css
  dist/core-styles.cms.css
  dist/elements/table--basic.css
  dist/elements/table--nested.css
  dist/elements/table.cms.css
  dist/elements/table.css
  fractal.config.js
  src/lib/_imports/elements/table--basic.css
  src/lib/_imports/elements/table--nested.css
  src/lib/_imports/elements/table.cms.css
  src/lib/_imports/elements/table.selectors.css
  src/lib/_imports/elements/table/table.hbs
Labels: feature, patch
