Repository TACC/Core-Styles, pull requests merged in 2024-02, with the labels that each got.

#306 refactor: font var names demote long promote short
  dist/core-styles.base.css
  dist/core-styles.settings.css
  dist/core-styles.wysiwyg.css
  dist/settings/font.css
  src/lib/_imports/settings/font.css
Labels: patch, chore

#307 hotfix: center text horizontally in button
  dist/components/c-button.css
  dist/components/c-form--login.css
  dist/components/c-form.css
  dist/core-styles.base.css
  dist/core-styles.settings.css
  dist/core-styles.wysiwyg.css
  dist/settings/font.css
  dist/trumps/s-form--login.css
  dist/trumps/s-form.css
  src/lib/_imports/components/c-button.css
Labels: fix, patch

#304 feat: des-2697 s-app-card & bootstrap 3 has-row--col-stretch-content-y
  dist/components/bootstrap.row.css
  dist/core-styles.cms.css
  dist/trumps/s-app-card.css
  dist/trumps/s-app-card/demo.css
  src/lib/_imports/components/bootstrap.row.css
  src/lib/_imports/tools/selectors.common.css
  src/lib/_imports/trumps/s-app-card.css
  src/lib/_imports/trumps/s-app-card/config.yml
  src/lib/_imports/trumps/s-app-card/demo.css
  src/lib/_imports/trumps/s-app-card/readme.md
  src/lib/_imports/trumps/s-app-card/s-app-card.hbs
Labels: feature

#311 hotfix: actually set hr color / fix typo
  src/lib/_imports/elements/html-elements.cms.css
Labels: fix, patch
