Repository TACC/Core-Styles, pull requests merged in 2024-04, with the labels that each got.

#324 CMD 105: CMS: Hero Banner Pattern
  dist/core-styles.cms.css
  dist/trumps/s-hero-banner.css
  dist/trumps/s-hero-banner/s-hero-banner.demo.css
  src/lib/_imports/core-styles.cms.css
  src/lib/_imports/trumps/s-hero-banner.css
  src/lib/_imports/trumps/s-hero-banner/config.yml
  src/lib/_imports/trumps/s-hero-banner/s-hero-banner.demo.css
  src/lib/_imports/trumps/s-hero-banner/s-hero-banner.hbs
Labels: feature, paused, minor

#328 fix: CMD-105 missing import for cusotm media q's
  dist/trumps/s-hero-banner.css
  src/lib/_imports/trumps/s-hero-banner.css
Labels: fix, patch

#329 fix: CMD-105 overflow on page w/ scrollbar
  src/lib/_imports/objects/o-section.css
  src/lib/_imports/trumps/s-hero-banner.css
Labels: fix, patch

#331 fix: cmd-105 cms hero banner pattern overflow
  dist/core-styles.cms.css
  dist/trumps/s-hero-banner.css
  src/lib/_imports/objects/o-section.css
  src/lib/_imports/trumps/s-hero-banner.css
Labels: fix, patch

#334 fix: des-2725 c-app-card--types not centered
  dist/components/c-app-card.css
  src/lib/_imports/components/c-app-card.css
Labels: fix

#332 docs: wp-280 @mixin supersedes @extend
  package.json
  src/.postcssrc.base.yml
  src/lib/_imports/components/admonition/readme.md
  src/lib/_imports/components/bootstrap.modal.css
  src/lib/_imports/components/django-cms-forms.hacks.css
  src/lib/_imports/objects/o-table-wrap/example.flexible-horz.css
  src/lib/_imports/tools/x-article-link.css
  src/lib/_imports/tools/x-center.css
  src/lib/_imports/tools/x-fake-border.css
  src/lib/_imports/tools/x-grid.css
  src/lib/_imports/tools/x-layout.css
  src/lib/_imports/tools/x-link.css
  src/lib/_imports/tools/x-link/demo.css
  src/lib/_imports/tools/x-link/readme.md
  src/lib/_imports/tools/x-link/x-link.hbs
  src/lib/_imports/tools/x-mailto-text-replace.css
  src/lib/_imports/tools/x-overlay.css
  src/lib/_imports/tools/x-truncate.css
Labels: documentation, patch
